services:
  
  sql:
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password@123
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"
  
  
  api:
    image: xenon1998/timingapp:latest
    restart: always
    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_URL: postgresql://root:pFZroHyJCPTl1LKOA8vpHkjH@reactivity:5432/postgres
    
    
    depends_on:
      - sql
      
    ports:
      - "80:8080"
