name: build and push to docker and publish to liara


on:
  push:
    branches:
      - liara-publish

jobs:
  build-dockerize-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          cache: 'false'
          dotnet-version: '8.0'
      - name: Build Project
        run: dotnet publish -c Release

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: xenon1998/vampire-diary:latest

      - name: Install Liara CLI
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Instal liara CLI
        run: npm i -g @liara/cli@7

      - name: Deploy
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        
        run:
          liara deploy --platform=docker --api-token="$LIARA_TOKEN" --no-app-logs